[package]
name = "dynfn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynfn-proc-macros = { path = "dynfn-proc-macros" }